const mainWeaponAttributes = {
  Milita: {},
  Bares: { attackSpeed: -2 },
  Yuria: { critChance: 2, attackSpeed: 3 },
  Azwell: {},
  Seleth: { attackSpeed: 5 },
  Hasseus: { attackSpeed: -2},
  Elisha: { critChance: 2, attackSpeed: 3 },
  Talis: {},
  Tirion: { critChance: 5 },
  Shamir: { attackSpeed: -2 },
  Kalas: { critChance: 3, attackSpeed: 2 },
  Mohrig: {},
  Romain: { attackSpeed: 5 },
  Liverato: { critChance: 5 },
  Kzarka: { critChance: 4, attackSpeed: 2 },
  Dandelion: { critChance: 2, attackSpeed: 4 },
};

const mainWeapon = [
  { type: 'Longsword', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 10, weight: 20, },
  { type: 'Longsword', variation: 'Bares', color: 'green', maxLevel: 15, gemSlots: 1, attack: 31, weight: 20, },
  { type: 'Longsword', variation: 'Yuria', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Longsword', variation: 'Azwell', color: 'green', maxLevel: 15, gemSlots: 1, attack: 27, weight: 20, },
  { type: 'Longsword', variation: 'Seleth', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Longsword', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 43, weight: 20, },
  { type: 'Longsword', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Longsword', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 39, weight: 20, },
  { type: 'Longsword', variation: 'Tirion', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Longsword', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 56, weight: 20, },
  { type: 'Longsword', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Longsword', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 52, weight: 20, },
  { type: 'Longsword', variation: 'Romain', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Longsword', variation: 'Liverato', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 66, weight: 20, },
  { type: 'Longsword', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 70, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 66, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Tirion', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 84, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 80, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Romain', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 95, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Bares', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 86, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Yuria', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Azwell', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 83, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Seleth', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Longsword', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 100, weight: 20, jin: true, },
  { type: 'Longsword', variation: 'Kzarka', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  { type: 'Longsword', variation: 'Dandelion', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  
  { type: 'Longbow', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 10, weight: 20, },
  { type: 'Longbow', variation: 'Bares', color: 'green', maxLevel: 15, gemSlots: 1, attack: 31, weight: 20, },
  { type: 'Longbow', variation: 'Yuria', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Longbow', variation: 'Azwell', color: 'green', maxLevel: 15, gemSlots: 1, attack: 27, weight: 20, },
  { type: 'Longbow', variation: 'Seleth', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Longbow', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 43, weight: 20, },
  { type: 'Longbow', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Longbow', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 39, weight: 20, },
  { type: 'Longbow', variation: 'Tirion', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Longbow', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 56, weight: 20, },
  { type: 'Longbow', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Longbow', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 52, weight: 20, },
  { type: 'Longbow', variation: 'Romain', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Longbow', variation: 'Liverato', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 66, weight: 20, },
  { type: 'Longbow', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 70, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 66, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Tirion', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 84, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 80, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Romain', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 95, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Bares', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 86, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Yuria', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Azwell', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 83, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Seleth', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Longbow', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 100, weight: 20, jin: true, },
  { type: 'Longbow', variation: 'Kzarka', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  { type: 'Longbow', variation: 'Dandelion', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  
  { type: 'Staff', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 10, weight: 20, },
  { type: 'Staff', variation: 'Bares', color: 'green', maxLevel: 15, gemSlots: 1, attack: 31, weight: 20, },
  { type: 'Staff', variation: 'Yuria', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Staff', variation: 'Azwell', color: 'green', maxLevel: 15, gemSlots: 1, attack: 27, weight: 20, },
  { type: 'Staff', variation: 'Seleth', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Staff', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 43, weight: 20, },
  { type: 'Staff', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Staff', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 39, weight: 20, },
  { type: 'Staff', variation: 'Tirion', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Staff', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 56, weight: 20, },
  { type: 'Staff', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Staff', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 52, weight: 20, },
  { type: 'Staff', variation: 'Romain', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Staff', variation: 'Liverato', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 66, weight: 20, },
  { type: 'Staff', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 70, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 66, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Tirion', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 84, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 80, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Romain', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 95, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Bares', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 86, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Yuria', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Azwell', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 83, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Seleth', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Staff', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 100, weight: 20, jin: true, },
  { type: 'Staff', variation: 'Kzarka', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  { type: 'Staff', variation: 'Dandelion', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  
  { type: 'Axe', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 10, weight: 20, },
  { type: 'Axe', variation: 'Bares', color: 'green', maxLevel: 15, gemSlots: 1, attack: 31, weight: 20, },
  { type: 'Axe', variation: 'Yuria', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Axe', variation: 'Azwell', color: 'green', maxLevel: 15, gemSlots: 1, attack: 27, weight: 20, },
  { type: 'Axe', variation: 'Seleth', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Axe', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 43, weight: 20, },
  { type: 'Axe', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Axe', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 39, weight: 20, },
  { type: 'Axe', variation: 'Tirion', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Axe', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 56, weight: 20, },
  { type: 'Axe', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Axe', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 52, weight: 20, },
  { type: 'Axe', variation: 'Romain', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Axe', variation: 'Liverato', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 66, weight: 20, },
  { type: 'Axe', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 70, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 66, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Tirion', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 84, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 80, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Romain', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 95, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Bares', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 86, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Yuria', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Azwell', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 83, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Seleth', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Axe', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 100, weight: 20, jin: true, },
  { type: 'Axe', variation: 'Kzarka', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  { type: 'Axe', variation: 'Dandelion', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  
  { type: 'Amulet', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 10, weight: 20, },
  { type: 'Amulet', variation: 'Bares', color: 'green', maxLevel: 15, gemSlots: 1, attack: 31, weight: 20, },
  { type: 'Amulet', variation: 'Yuria', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Amulet', variation: 'Azwell', color: 'green', maxLevel: 15, gemSlots: 1, attack: 27, weight: 20, },
  { type: 'Amulet', variation: 'Seleth', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Amulet', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 43, weight: 20, },
  { type: 'Amulet', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Amulet', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 39, weight: 20, },
  { type: 'Amulet', variation: 'Tirion', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Amulet', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 56, weight: 20, },
  { type: 'Amulet', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Amulet', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 52, weight: 20, },
  { type: 'Amulet', variation: 'Romain', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Amulet', variation: 'Liverato', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 66, weight: 20, },
  { type: 'Amulet', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 70, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 66, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Tirion', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 84, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 80, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Romain', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 95, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Bares', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 86, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Yuria', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Azwell', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 83, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Seleth', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Amulet', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 100, weight: 20, jin: true, },
  { type: 'Amulet', variation: 'Kzarka', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  { type: 'Amulet', variation: 'Dandelion', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  
  { type: 'Kriegsmesser', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 10, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Bares', color: 'green', maxLevel: 15, gemSlots: 1, attack: 31, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Yuria', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Azwell', color: 'green', maxLevel: 15, gemSlots: 1, attack: 27, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Seleth', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 43, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 39, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Tirion', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 56, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 52, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Romain', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Liverato', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 66, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 70, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 66, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Tirion', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 84, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 80, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Romain', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 95, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Bares', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 86, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Yuria', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Azwell', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 83, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Seleth', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Kriegsmesser', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 100, weight: 20, jin: true, },
  { type: 'Kriegsmesser', variation: 'Kzarka', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  { type: 'Kriegsmesser', variation: 'Dandelion', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  
  { type: 'Gauntlet', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 10, weight: 20, },
  { type: 'Gauntlet', variation: 'Bares', color: 'green', maxLevel: 15, gemSlots: 1, attack: 31, weight: 20, },
  { type: 'Gauntlet', variation: 'Yuria', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Gauntlet', variation: 'Azwell', color: 'green', maxLevel: 15, gemSlots: 1, attack: 27, weight: 20, },
  { type: 'Gauntlet', variation: 'Seleth', color: 'green', maxLevel: 15, gemSlots: 1, attack: 23, weight: 20, },
  { type: 'Gauntlet', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 43, weight: 20, },
  { type: 'Gauntlet', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Gauntlet', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 39, weight: 20, },
  { type: 'Gauntlet', variation: 'Tirion', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 35, weight: 20, },
  { type: 'Gauntlet', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 56, weight: 20, },
  { type: 'Gauntlet', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Gauntlet', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 52, weight: 20, },
  { type: 'Gauntlet', variation: 'Romain', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 48, weight: 20, },
  { type: 'Gauntlet', variation: 'Liverato', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 66, weight: 20, },
  { type: 'Gauntlet', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 70, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 66, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Tirion', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 62, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 84, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 80, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Romain', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 76, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 95, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Bares', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 86, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Yuria', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Azwell', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 83, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Seleth', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 80, weight: 20, ultimate: true, },
  { type: 'Gauntlet', variation: 'Liverato', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 100, weight: 20, jin: true, },
  { type: 'Gauntlet', variation: 'Kzarka', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
  { type: 'Gauntlet', variation: 'Dandelion', color: 'red', maxLevel: 40, gemSlots: 2, attack: 135, weight: 20, },
];

const subWeaponAttributes = {
  Militia: {},
  Axion: { critChance: 3, attackSpeed: 3 },
  Vangertz: { moveSpeed: 3, attackSpeed: 3 },
  Krea: { critChance: 5 },
  Hasseus: { critChance: 5 },
  Elisha: { critChance: 3, attackSpeed: 3 },
  Talis: { moveSpeed: 3, attackSpeed: 3 },
  Shamir: { critChance: 5 },
  Kalas: { critChance: 3, attackSpeed: 3 },
  Mohrig: { moveSpeed: 3, attackSpeed: 3 },
  Kite: { critChance: 3, moveSpeed: 3 },
  Nouver: { critChance: 5, moveSpeed: 3 },
};

const subWeapon = [
  { type: 'Shield', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 7, defense: 2, weight: 6, },
  { type: 'Shield', variation: 'Axion', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Shield', variation: 'Vangertz', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Shield', variation: 'Krea', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Shield', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Shield', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Shield', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Shield', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Shield', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Shield', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Shield', variation: 'Kite', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 41, defense: 13, weight: 6, },
  { type: 'Shield', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 59, defense: 19, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Axion', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Vangertz', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Krea', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Shield', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 63, defense: 20, weight: 6, jin: true, },
  { type: 'Shield', variation: 'Nouver', color: 'red', maxLevel: 40, gemSlots: 2, attack: 84, defense: 38, weight: 6, },

  { type: 'Dagger', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 7, defense: 2, weight: 6, },
  { type: 'Dagger', variation: 'Axion', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Dagger', variation: 'Vangertz', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Dagger', variation: 'Krea', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Dagger', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Dagger', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Dagger', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Dagger', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Dagger', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Dagger', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Dagger', variation: 'Kite', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 41, defense: 13, weight: 6, },
  { type: 'Dagger', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 59, defense: 19, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Axion', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Vangertz', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Krea', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Dagger', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 63, defense: 20, weight: 6, jin: true, },
  { type: 'Dagger', variation: 'Nouver', color: 'red', maxLevel: 40, gemSlots: 2, attack: 84, defense: 38, weight: 6, },

  { type: 'Ornamental Knot', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 7, defense: 2, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Axion', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Vangertz', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Krea', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Kite', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 41, defense: 13, weight: 6, },
  { type: 'Ornamental Knot', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 59, defense: 19, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Axion', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Vangertz', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Krea', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Ornamental Knot', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 63, defense: 20, weight: 6, jin: true, },
  { type: 'Ornamental Knot', variation: 'Nouver', color: 'red', maxLevel: 40, gemSlots: 2, attack: 84, defense: 38, weight: 6, },

  { type: 'Talisman', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 7, defense: 2, weight: 6, },
  { type: 'Talisman', variation: 'Axion', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Talisman', variation: 'Vangertz', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Talisman', variation: 'Krea', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Talisman', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Talisman', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Talisman', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Talisman', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Talisman', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Talisman', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Talisman', variation: 'Kite', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 41, defense: 13, weight: 6, },
  { type: 'Talisman', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 59, defense: 19, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Axion', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Vangertz', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Krea', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Talisman', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 63, defense: 20, weight: 6, jin: true, },
  { type: 'Talisman', variation: 'Nouver', color: 'red', maxLevel: 40, gemSlots: 2, attack: 84, defense: 38, weight: 6, },

  { type: 'Vambrace', variation: 'Militia', color: 'white', maxLevel: 10, gemSlots: 1, attack: 7, defense: 2, weight: 6, },
  { type: 'Vambrace', variation: 'Axion', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Vambrace', variation: 'Vangertz', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Vambrace', variation: 'Krea', color: 'green', maxLevel: 15, gemSlots: 1, attack: 17, defense: 5, weight: 6, },
  { type: 'Vambrace', variation: 'Hasseus', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Vambrace', variation: 'Elisha', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Vambrace', variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, attack: 25, defense: 8, weight: 6, },
  { type: 'Vambrace', variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Vambrace', variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Vambrace', variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, attack: 33, defense: 10, weight: 6, },
  { type: 'Vambrace', variation: 'Kite', color: 'yellow', maxLevel: 40, gemSlots: 2, attack: 41, defense: 13, weight: 6, },
  { type: 'Vambrace', variation: 'Hasseus', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Elisha', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, attack: 41, defense: 13, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, attack: 50, defense: 16, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 59, defense: 19, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Axion', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Vangertz', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Krea', color: 'orange', maxLevel: 40, gemSlots: 2, attack: 53, defense: 17, weight: 6, ultimate: true, },
  { type: 'Vambrace', variation: 'Kite', color: 'orange', maxLevel: 40, gemSlots: 3, attack: 63, defense: 20, weight: 6, jin: true, },
  { type: 'Vambrace', variation: 'Nouver', color: 'red', maxLevel: 40, gemSlots: 2, attack: 84, defense: 38, weight: 6, },
];

const helmetAttributes = {
  Reblath: {},
  Zereth: { critChance: 4 },
  Taritas: { critChance: -2 },
  Agerian: { mana: 10, magicRegen: 1 },
  Talis: { critChance: 4 },
  Dobart: { critChance: -2 },
  Rocaba: { mana: 10, magicRegen: 1 },
  Kalas: { critChance: 4 },
  Shamir: { critChance: -2 },
  Mohrig: { mana: 10, magicRegen: 1 },
  Grunil: { critChance: 4 },
  Azerian: { MPRegen: 2, magicRegen: 2 },
  'Giath\s': { critChance: 5 },
  'Guy Seric': { critChance: 2.5, attackSpeed: 2.5 },
  Shultz: { attackSpeed: 5 },
  Rakshan: { critChance: 2.5, moveSpeed: 2.5 },
};

const helmet = [
  { variation: 'Reblath', color: 'white', maxLevel: 10, gemSlots: 1, defense: 5, weight: 8, },
  { variation: 'Zereth', color: 'green', maxLevel: 15, gemSlots: 1, defense: 11, weight: 8, },
  { variation: 'Taritas', color: 'green', maxLevel: 15, gemSlots: 1, defense: 15, weight: 8, },
  { variation: 'Agerian', color: 'green', maxLevel: 15, gemSlots: 1, defense: 13, weight: 8, },
  { variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 16, weight: 8, },
  { variation: 'Dobart', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 20, weight: 8, },
  { variation: 'Rocaba', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 18, weight: 8, },
  { variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 22, weight: 8, },
  { variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 26, weight: 8, },
  { variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 24, weight: 8, },
  { variation: 'Grunil', color: 'yellow', maxLevel: 40, gemSlots: 2, defense: 31, weight: 8, },
  { variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 29, weight: 8, ultimate: true },
  { variation: 'Dobart', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 33, weight: 8, ultimate: true },
  { variation: 'Rocaba', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 31, weight: 8, ultimate: true },
  { variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 41, weight: 8, ultimate: true },
  { variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 45, weight: 8, ultimate: true },
  { variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 43, weight: 8, ultimate: true },
  { variation: 'Grunil', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 55, weight: 8, ultimate: true },
  { variation: 'Zereth', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 44, weight: 8, ultimate: true },
  { variation: 'Taritas', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 48, weight: 8, ultimate: true },
  { variation: 'Azerian', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 46, weight: 8, ultimate: true },
  { variation: 'Grunil', color: 'orange', maxLevel: 40, gemSlots: 3, defense: 58, weight: 8, jin: true },
  { variation: 'Giath\'s', color: 'red', maxLevel: 40, gemSlots: 2, defense: 95, weight: 8, },
  { variation: 'Guy Seric', color: 'red', maxLevel: 40, gemSlots: 2, defense: 95, weight: 8, },
  { variation: 'Shultz', color: 'red', maxLevel: 40, gemSlots: 2, defense: 95, weight: 8, },
  { variation: 'Rakshan', color: 'red', maxLevel: 40, gemSlots: 2, defense: 95, weight: 8, },
];

const armorAttributes = {
  Reblath: {},
  Zereth: { mana: 20, magicRegen: 2 },
  Taritas: { moveSpeed: -1, mana: -20, magicRegen: -2 },
  Agerian: { MPRegen: 2, magicRegen: 2 },
  Talis: { mana: 20, magicRegen: 2 },
  Dobart: { moveSpeed: -1, mana: -20, magicRegen: -2 },
  Rocaba: { MPRegen: 2, magicRegen: 2 },
  Kalas: { mana: 20, magicRegen: 2 },
  Shamir: { moveSpeed: -1, mana: -20, magicRegen: -2 },
  Mohrig: { MPRegen: 2, magicRegen: 2 },
  Grunil: { mana: 20, magicRegen: 2 },
  Azerian: { MPRegen: 2, magicRegen: 2 },
  'Red Nose': { HP: 200, mana: 20, magicRegen: 2 },
  Shultz: { HP: 200, MPRegen: 2, magicRegen: 2 },
};

const armor = [
  { variation: 'Reblath', color: 'white', maxLevel: 10, gemSlots: 1, defense: 7, weight: 15, },
  { variation: 'Zereth', color: 'green', maxLevel: 15, gemSlots: 1, defense: 17, weight: 15, },
  { variation: 'Taritas', color: 'green', maxLevel: 15, gemSlots: 1, defense: 21, weight: 15, },
  { variation: 'Agerian', color: 'green', maxLevel: 15, gemSlots: 1, defense: 19, weight: 15, },
  { variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 25, weight: 15, },
  { variation: 'Dobart', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 29, weight: 15, },
  { variation: 'Rocaba', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 27, weight: 15, },
  { variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 34, weight: 15, },
  { variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 38, weight: 15, },
  { variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 36, weight: 15, },
  { variation: 'Grunil', color: 'yellow', maxLevel: 40, gemSlots: 2, defense: 46, weight: 15, },
  { variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 44, weight: 15, ultimate: true },
  { variation: 'Dobart', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 48, weight: 15, ultimate: true },
  { variation: 'Rocaba', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 46, weight: 15, ultimate: true },
  { variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 54, weight: 15, ultimate: true },
  { variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 58, weight: 15, ultimate: true },
  { variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 56, weight: 15, ultimate: true },
  { variation: 'Grunil', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 71, weight: 15, ultimate: true },
  { variation: 'Zereth', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 59, weight: 15, ultimate: true },
  { variation: 'Taritas', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 63, weight: 15, ultimate: true },
  { variation: 'Azerian', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 61, weight: 15, ultimate: true },
  { variation: 'Grunil', color: 'orange', maxLevel: 40, gemSlots: 3, defense: 75, weight: 15, jin: true },
  { variation: 'Red Nose', color: 'red', maxLevel: 40, gemSlots: 2, defense: 111, weight: 15, },
  { variation: 'Shultz', color: 'red', maxLevel: 40, gemSlots: 2, defense: 111, weight: 15, },
];

const gloveAttributes = {
  Reblath: {},
  Zereth: { attackSpeed: 4 },
  Taritas: { attackSpeed: -2 },
  Agerian: { mana: 10, magicRegen: 1 },
  Talis: { attackSpeed: 4 },
  Dobart: { attackSpeed: -2 },
  Rocaba: { mana: 10, magicRegen: 1 },
  Kalas: { attackSpeed: 4 },
  Shamir: { attackSpeed: -2 },
  Mohrig: { mana: 10, magicRegen: 1 },
  Grunil: { attackSpeed: 4 },
  Azerian: { mana: 10, magicRegen: 1 },
  'Bheg\'s': { attackSpeed: 5 },
  'Noir\'s': { critChance: 2.5, attackSpeed: 2.5 },
  Rakshan: { attackSpeed: 5 },
};

const glove = [
  { variation: 'Reblath', color: 'white', maxLevel: 10, gemSlots: 1, defense: 2, weight: 5, },
  { variation: 'Zereth', color: 'green', maxLevel: 15, gemSlots: 1, defense: 3, weight: 5, },
  { variation: 'Taritas', color: 'green', maxLevel: 15, gemSlots: 1, defense: 7, weight: 5, },
  { variation: 'Agerian', color: 'green', maxLevel: 15, gemSlots: 1, defense: 5, weight: 5, },
  { variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 7, weight: 5, },
  { variation: 'Dobart', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 11, weight: 5, },
  { variation: 'Rocaba', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 9, weight: 5, },
  { variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 12, weight: 5, },
  { variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 16, weight: 5, },
  { variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 14, weight: 5, },
  { variation: 'Grunil', color: 'yellow', maxLevel: 40, gemSlots: 2, defense: 19, weight: 5, },
  { variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 17, weight: 5, ultimate: true },
  { variation: 'Dobart', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 21, weight: 5, ultimate: true },
  { variation: 'Rocaba', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 19, weight: 5, ultimate: true },
  { variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 28, weight: 5, ultimate: true },
  { variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 32, weight: 5, ultimate: true },
  { variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 30, weight: 5, ultimate: true },
  { variation: 'Grunil', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 38, weight: 5, ultimate: true },
  { variation: 'Zereth', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 30, weight: 5, ultimate: true },
  { variation: 'Taritas', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 34, weight: 5, ultimate: true },
  { variation: 'Azerian', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 32, weight: 5, ultimate: true },
  { variation: 'Grunil', color: 'orange', maxLevel: 40, gemSlots: 3, defense: 40, weight: 5, jin: true },
  { variation: 'Bheg\'s', color: 'red', maxLevel: 40, gemSlots: 2, defense: 78, weight: 5, },
  { variation: 'Noir\'s', color: 'red', maxLevel: 40, gemSlots: 2, defense: 78, weight: 5, },
  { variation: 'Rakshan', color: 'red', maxLevel: 40, gemSlots: 2, defense: 78, weight: 5, },
];

const shoeAttributes = {
  Reblath: {},
  Zereth: { moveSpeed: 4 },
  Taritas: { moveSpeed: -2 },
  Agerian: { mana: 10, magicRegen: 1 },
  Talis: { moveSpeed: 4 },
  Dobart: { moveSpeed: -2 },
  Rocaba: { mana: 10, magicRegen: 1 },
  Kalas: { moveSpeed: 4 },
  Shamir: { moveSpeed: -2 },
  Mohrig: { mana: 10, magicRegen: 1 },
  Grunil: { moveSpeed: 4 },
  Azerian: { mana: 10, magicRegen: 1 },
  'Muskan\'s': { moveSpeed: 5 },
  'Noir\'s': { critChance: 2.5, moveSpeed: 2.5 },
  'Guy Seric': { attackSpeed: 2.5, moveSpeed: 2.5 },
  Rakshan: { critChance: 5 },
};

const shoe = [
  { variation: 'Reblath', color: 'white', maxLevel: 10, gemSlots: 1, defense: 2, weight: 5, },
  { variation: 'Zereth', color: 'green', maxLevel: 15, gemSlots: 1, defense: 3, weight: 5, },
  { variation: 'Taritas', color: 'green', maxLevel: 15, gemSlots: 1, defense: 7, weight: 5, },
  { variation: 'Agerian', color: 'green', maxLevel: 15, gemSlots: 1, defense: 5, weight: 5, },
  { variation: 'Talis', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 7, weight: 5, },
  { variation: 'Dobart', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 11, weight: 5, },
  { variation: 'Rocaba', color: 'blue', maxLevel: 20, gemSlots: 1, defense: 9, weight: 5, },
  { variation: 'Kalas', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 12, weight: 5, },
  { variation: 'Shamir', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 16, weight: 5, },
  { variation: 'Mohrig', color: 'purple', maxLevel: 25, gemSlots: 1, defense: 14, weight: 5, },
  { variation: 'Grunil', color: 'yellow', maxLevel: 40, gemSlots: 2, defense: 19, weight: 5, },
  { variation: 'Talis', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 17, weight: 5, ultimate: true },
  { variation: 'Dobart', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 21, weight: 5, ultimate: true },
  { variation: 'Rocaba', color: 'yellow', maxLevel: 40, gemSlots: 1, defense: 19, weight: 5, ultimate: true },
  { variation: 'Kalas', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 28, weight: 5, ultimate: true },
  { variation: 'Shamir', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 32, weight: 5, ultimate: true },
  { variation: 'Mohrig', color: 'orange', maxLevel: 40, gemSlots: 1, defense: 30, weight: 5, ultimate: true },
  { variation: 'Grunil', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 38, weight: 5, ultimate: true },
  { variation: 'Zereth', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 30, weight: 5, ultimate: true },
  { variation: 'Taritas', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 34, weight: 5, ultimate: true },
  { variation: 'Azerian', color: 'orange', maxLevel: 40, gemSlots: 2, defense: 32, weight: 5, ultimate: true },
  { variation: 'Grunil', color: 'orange', maxLevel: 40, gemSlots: 3, defense: 40, weight: 5, jin: true },
  { variation: 'Muskan\'s', color: 'red', maxLevel: 40, gemSlots: 2, defense: 78, weight: 5, },
  { variation: 'Noir\'s', color: 'red', maxLevel: 40, gemSlots: 2, defense: 78, weight: 5, },
  { variation: 'Guy Seric', color: 'red', maxLevel: 40, gemSlots: 2, defense: 78, weight: 5, },
  { variation: 'Rakshan', color: 'red', maxLevel: 40, gemSlots: 2, defense: 78, weight: 5, },
];

module.exports = {
  mainWeaponAttributes,
  mainWeapon,
  subWeaponAttributes,
  subWeapon,
  helmetAttributes,
  Helmet: helmet,
  armorAttributes,
  Armor: armor,
  gloveAttributes,
  Glove: glove,
  shoeAttributes,
  Shoe: shoe,
};
